# Generated by Django 5.1.5 on 2025-03-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine', models.CharField(max_length=100)),
                ('cylinders', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('drivetrain', models.CharField(max_length=50)),
            ],
        ),
    ]
