# Generated by Django 5.1.5 on 2025-03-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_vehicle_cylinders_alter_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cylinders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(),
        ),
    ]
